import Foundation

/// Context handoff between agents working in the same worktree. Because sessions share
/// the working dir, the receiving agent already has the code — the handoff carries the
/// *intent*: goal, decisions, state, what's left. Two authoring modes: ask the current
/// agent to write it (rich), or have GingerPaw generate it from git state (instant).
enum Handoff {
    static let fileName = "HANDOFF.md"

    static func path(_ worktreePath: String) -> String {
        (worktreePath as NSString).appendingPathComponent(fileName)
    }

    /// Injected into the live agent so it writes the handoff itself (it has the full context).
    static var authorPrompt: String {
        """
        Write a file named HANDOFF.md in the repository root so another coding agent can pick up \
        your work. The other agent shares this exact working directory — it already has the code, \
        so don't restate the diff. Focus on intent: the goal, what you've done so far, key decisions \
        and *why*, the current state, what's left to do, and any gotchas. Keep it concise. Write only the file.
        """
    }

    /// Seeds a freshly-spawned agent to resume from the handoff.
    static var continuePrompt: String {
        "A previous agent left context in HANDOFF.md at the repository root. Read it first, then continue the work."
    }

    /// Instant, factual handoff from what GingerPaw can see (no agent round-trip).
    static func generated(branch: String, worktreePath: String, scrollback: String) -> String {
        let files = GitWorktrees.changedFiles(worktreePath)
        let fileLines = files.isEmpty ? "_(none)_" : files.map { "- `\($0.path)` (\($0.status), +\($0.insertions) −\($0.deletions))" }.joined(separator: "\n")
        let log = GitWorktrees.runRaw(["-C", worktreePath, "log", "--oneline", "-10"]).trimmingCharacters(in: .whitespacesAndNewlines)
        let logBlock = log.isEmpty ? "_(no commits on this branch yet)_" : "```\n\(log)\n```"
        let scroll = scrollback.trimmingCharacters(in: .whitespacesAndNewlines)
        let scrollBlock = scroll.isEmpty ? "_(no captured session output)_" : "```\n\(scroll.suffix(3000))\n```"
        return """
        # Handoff

        > Auto-generated by GingerPaw from git state. The code is in this same worktree.

        **Branch:** `\(branch)`

        ## Changed files
        \(fileLines)

        ## Recent commits
        \(logBlock)

        ## Recent session output (scraped)
        \(scrollBlock)

        ## What's left
        _Fill in or ask the previous agent — this was generated without its reasoning._
        """
    }

    static func write(_ content: String, to worktreePath: String) {
        try? content.write(toFile: path(worktreePath), atomically: true, encoding: .utf8)
        excludeFromGit(worktreePath)
    }

    static func read(_ worktreePath: String) -> String? {
        try? String(contentsOfFile: path(worktreePath), encoding: .utf8)
    }

    /// (exists, byte size) — drives the "writing… / ready" status while polling.
    static func status(_ worktreePath: String) -> (exists: Bool, size: Int) {
        let attrs = try? FileManager.default.attributesOfItem(atPath: path(worktreePath))
        let size = (attrs?[.size] as? Int) ?? 0
        return (attrs != nil, size)
    }

    /// Keep HANDOFF.md out of the agent's diff/PR (same approach as MCPConfig).
    static func excludeFromGit(_ worktreePath: String) {
        var p = GitWorktrees.runRaw(["-C", worktreePath, "rev-parse", "--git-path", "info/exclude"])
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !p.isEmpty else { return }
        if !p.hasPrefix("/") { p = (worktreePath as NSString).appendingPathComponent(p) }
        let existing = (try? String(contentsOfFile: p, encoding: .utf8)) ?? ""
        guard !existing.contains(fileName) else { return }
        try? (existing + (existing.isEmpty ? "" : "\n") + fileName + "\n").write(toFile: p, atomically: true, encoding: .utf8)
    }
}
